### ISSUE TITLE
LogInfo: Not required: <atlas_name> + Dataset <name> is not a derivatives dataset. Skipping.

### ISSUE THREAD

**Issue by LuRoe7** [PennLINC/xcp_d#1412]
## Summary
I want to run xcp_d using a custom confound regression strategy including white matter signal, CSF signal, global signal and AROMA motion confounds. I first ran fmriprep v24.0.0 on my data (without AROMA) followed by fmripost-aroma v0.1. Furthermore, I aim to use a custom brain atlas (Brainnetome). xcp_d runs without errors, but in the logs it says the following:

> Not required: brainnetome
> Dataset aroma is not a derivatives dataset. Skipping.

## Additional details

- xcp_d version: 0.10.6
- Docker version: -
- Singularity version: 3.7.1

### What were you trying to do?
see summary

### What did you expect to happen?
I expected to receive denoised rs-fMRI data (WM, CSF, Global Signal + AROMA Motion Components) and functional connectivity matrices based on the Brainnetome parcellation

### What actually happened?
It seems that xcp_d does not recognize my custom atlas (Brainnetome) and the fmripost-aroma directory.

> Not required: brainnetome
> Dataset aroma is not a derivatives dataset. Skipping.

## Reproducing the bug

Here is the singularity run command:

```
singularity run --cleanenv --home /data/tmp/cdp/xcpd \
    -B /data/datasets/cdp/derivatives/fmriprep:/data \
    -B /data/datasets/cdp/derivatives/xcpd:/out \
    -B /data/atlases_bids/brainnetome:/data/atlases_bids/brainnetome \
    -B /data/datasets/cdp/derivatives/fmripost-aroma:/fpostaroma \
    -B /data/scripts/yaml:/config \
    -B /data/wd/cdp/xcpd:/workdir \
    -B /data/fslicense:/freesurfer \
    /data/images/xcpd-0.10.6.sif \
    /data /out participant \
    --datasets brainnetome=/data/atlases_bids/brainnetome aroma=/fpostaroma \
    --mode none \
    --input-type fmriprep \
    --file-format nifti \
    --participant-label ${CDP_ID} \
    --nprocs 2 \
    --mem-gb 4 \
    --fs-license-file /freesurfer/license.txt \
    --dummy-scans 10 \
    --nuisance-regressors /config/ICAAROMA2Phys1GS.yaml \
    --despike y \
    --smoothing 6 \
    --combine-runs n \
    --motion-filter-type notch \
    --band-stop-min 12 \
    --band-stop-max 18 \
    --head-radius 50 \
    --fd-thresh 0.5 \
    --min-time 300 \
    --output-type censored \
    --lower-bpf 0.01 \
    --upper-bpf 0.08 \
    --bpf-order 2 \
    --atlases Brainnetome Glasser \
    --min-coverage 0.5 \
    --abcc-qc y \
    --linc-qc y \
    --warp-surfaces-native2std n \
    --aggregate-session-reports 10 \
    --work-dir /workdir \
    --debug all
```

This is the BIDS Atlas directory:
> tree /data/atlases_bids/brainnetome
> /data/atlases_bids/brainnetome
> ├── atlas-Brainnetome
> │   ├── atlas-Brainnetome_dseg.tsv
> │   ├── atlas-Brainnetome_space-MNI152NLin6Asym_res-2_dseg.json
> │   └── atlas-Brainnetome_space-MNI152NLin6Asym_res-2_dseg.nii.gz
> └── dataset_description.json

This is the dataset_description.json file within the atlas directory:

```
{
    "BIDSVersion": "1.4.0",
    "Name": "Brainnetome",
    "DatasetType":"atlas",
    "Authors": [
        "My Name"
    ],
    "License": "CC-BY",
    "Funding": ["No funding yet"],
    "ReferencesAndLinks": [
        "https://pubmed.ncbi.nlm.nih.gov/35488054/"
    ]
}

```

This is the config yaml file specifying the denoising strategy:

```
name: aroma_gsr
description: |
   Nuisance regressors were selected according to the 'aroma_gsr' strategy.
   AROMA motion-labeled components [@pruim2015ica], mean white matter signal,
   mean cerebrospinal fluid signal, and mean global signal were selected as
   nuisance regressors [@benchmarkp;@satterthwaite_2013].
confounds:
   preproc_confounds:
      dataset: preprocessed
      query:
         space: null
         cohort: null
         res: null
         den: null
         desc: confounds
         extension: .tsv
         suffix: timeseries
      columns:
      - global_signal
      - csf
      - white_matter
   aroma_confounds:
      dataset: aroma
      query:
         space: null
         cohort: null
         res: null
         den: null
         desc: aroma
         extension: .tsv
         suffix: timeseries
      columns:
      - ^aroma_orth_motion_.*$

```

And finally, this is the dataset_description.json file within the fmripost-aroma directory (DatasetType is specified):

```
{
    "BIDSVersion": "1.9.0dev",
    "Name": "fMRIPost-AROMA- ICA-AROMA Postprocessing Outputs",
    "Authors": [
        "My Name"
    ],
    "License": "CC-BY",
    "Funding": [
        "No funding yet"
    ],
    "ReferencesAndLinks": [
        "https://osf.io/tr3nx/?view_only=d2b15fb0503043328a7a27d0ba3a801f",
        "https://pubmed.ncbi.nlm.nih.gov/35488054/"
    ],
    "DatasetType": "derivative",
    "HowToAcknowledge": "Include the generated boilerplate in the methods section.",
    "GeneratedBy": [
        {
            "Name": "fMRIPost-AROMA",
            "Version": "0.1.dev1+ga90f01f",
            "CodeURL": "https://github.com/nipreps/fmripost_aroma/archive/0.1.dev1+ga90f01f.tar.gz"
        }
    ],
    "DatasetLinks": {
        "input": "/data",
        "templateflow": "https://github.com/templateflow/templateflow",
        "fmriprep": "/data/derivatives/fmriprep"
    }
}

```
